import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
import { SUPABASE_URL, SUPABASE_KEY } from "../supabase-config.js";

const STORAGE_KEY="b612_scent_vault_v1";
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
let pendingImport=null;

function injectStyles(){if(document.getElementById("parfumoImportStyles"))return;const s=document.createElement("style");s.id="parfumoImportStyles";s.textContent=`
.parfumo-import{grid-column:span 2;border:1px solid var(--line);border-radius:16px;padding:14px;background:color-mix(in srgb,var(--panel) 92%,var(--accent2) 8%);display:grid;gap:10px}.parfumo-import-head strong{font-size:.9rem}.parfumo-import-head span{font-size:.72rem;color:var(--muted)}.parfumo-import-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px}.parfumo-import-row input{margin:0!important}.parfumo-import-row button,.parfumo-import-actions button{padding:10px 13px;border-radius:12px;border:1px solid var(--line);font-weight:750}.parfumo-import-row button,.parfumo-import-actions .primary-import{background:var(--ink);color:var(--bg);border-color:var(--ink)}.parfumo-import-actions{display:flex;gap:8px;flex-wrap:wrap}.parfumo-status{font-size:.78rem;line-height:1.45;color:var(--muted)}.parfumo-status.ok{color:var(--accent)}.parfumo-status.error{color:var(--danger)}.parfumo-suggestions{display:grid;gap:8px}.parfumo-suggestion{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:center;text-align:left;padding:10px 12px;border:1px solid var(--line);border-radius:12px;background:var(--panel)}.parfumo-suggestion strong{display:block;font-size:.86rem}.parfumo-suggestion small{display:block;color:var(--muted);margin-top:2px}.parfumo-suggestion span:last-child{font-size:.72rem;font-weight:800;color:var(--accent)}.parfumo-preview{display:none;grid-template-columns:72px minmax(0,1fr);gap:12px;align-items:center}.parfumo-preview.show{display:grid}.parfumo-preview img{width:72px;height:82px;object-fit:contain;border:1px solid var(--line);border-radius:12px;background:#fff;padding:5px}.parfumo-preview strong{display:block}.parfumo-preview small{display:block;color:var(--muted);margin-top:3px;line-height:1.4}@media(max-width:560px){.parfumo-import{grid-column:span 1}.parfumo-import-row{grid-template-columns:1fr}.parfumo-import-row button{width:100%}.parfumo-import-actions{display:grid;grid-template-columns:1fr 1fr}.parfumo-import-actions button{width:100%}}
`;document.head.appendChild(s)}

function ensureUi(){if(document.getElementById("parfumoImport"))return;const name=document.getElementById("name"),grid=name?.closest(".form-grid");if(!name||!grid)return;const box=document.createElement("div");box.id="parfumoImport";box.className="parfumo-import";box.innerHTML=`<div class="parfumo-import-head"><strong>Parfumo</strong><span> · pesquisar e preencher ficha</span></div><div class="parfumo-import-row"><input id="parfumoUrl" type="url" inputmode="url" placeholder="URL da ficha Parfumo (opcional)"><button type="button" id="parfumoFetch">Importar URL</button></div><div class="parfumo-import-actions"><button type="button" id="parfumoSearch" class="primary-import">Pesquisar nome / marca</button><button type="button" id="parfumoClear">Limpar</button></div><div id="parfumoStatus" class="parfumo-status">Podes pesquisar só por nome, só por marca, ou pelos dois.</div><div id="parfumoSuggestions" class="parfumo-suggestions"></div><div id="parfumoPreview" class="parfumo-preview"><img id="parfumoPreviewImg" alt=""><div><strong id="parfumoPreviewName"></strong><small id="parfumoPreviewMeta"></small></div></div>`;const label=name.closest("label");label?.nextSibling?grid.insertBefore(box,label.nextSibling):grid.appendChild(box);document.getElementById("parfumoFetch")?.addEventListener("click",()=>importByUrl());document.getElementById("parfumoSearch")?.addEventListener("click",()=>searchParfumo());document.getElementById("parfumoClear")?.addEventListener("click",clearImport)}
function status(t,type=""){const e=document.getElementById("parfumoStatus");if(e){e.textContent=t;e.className=`parfumo-status ${type}`.trim()}}
function clearSuggestions(){const e=document.getElementById("parfumoSuggestions");if(e)e.innerHTML=""}
function clearImport(){pendingImport=null;document.getElementById("parfumoPreview")?.classList.remove("show");const u=document.getElementById("parfumoUrl");if(u)u.value="";clearSuggestions();status("Podes pesquisar só por nome, só por marca, ou pelos dois.")}
async function ensureSession(){const {data}=await supabase.auth.getSession();if(data.session)return data.session;const {data:a,error}=await supabase.auth.signInAnonymously();if(error)throw error;return a.session}
async function invoke(body){await ensureSession();const {data,error}=await supabase.functions.invoke("parfumo-import",{body});if(error){const msg=error?.context?.body?.error||error?.message||"Falha ao consultar o Parfumo.";throw new Error(msg)}if(data?.error)throw new Error(data.error);return data}
function setBusy(v){["parfumoFetch","parfumoSearch"].forEach(id=>{const b=document.getElementById(id);if(b)b.disabled=v})}
async function searchParfumo(){setBusy(true);clearSuggestions();status("A procurar opções no Parfumo…");try{const brand=(document.getElementById("brand")?.value||"").trim(),name=(document.getElementById("name")?.value||"").trim();if(!brand&&!name)throw new Error("Escreve pelo menos parte do nome ou da marca.");const data=await invoke({brand,name,mode:"suggest"});const list=Array.isArray(data?.suggestions)?data.suggestions:[];if(!list.length){status("Não encontrei opções. Experimenta outra parte do nome/marca ou cola o URL da ficha.","error");return}renderSuggestions(list);status(`${list.length} opção${list.length===1?"":"ões"} encontrada${list.length===1?"":"s"}. Escolhe a ficha certa.`)}catch(e){console.warn(e);status(e?.message||"Não foi possível pesquisar no Parfumo.","error")}finally{setBusy(false)}}
function renderSuggestions(list){const host=document.getElementById("parfumoSuggestions");if(!host)return;host.innerHTML="";list.forEach(c=>{const b=document.createElement("button");b.type="button";b.className="parfumo-suggestion";b.innerHTML=`<span><strong>${esc(c.title||"Perfume")}</strong><small>${esc(c.brand||"Marca desconhecida")}</small></span><span>Selecionar</span>`;b.addEventListener("click",()=>loadSuggestion(c.url));host.appendChild(b)})}
async function loadSuggestion(url){setBusy(true);status("A carregar a ficha selecionada…");try{const data=await invoke({url});if(!data?.perfume)throw new Error("A ficha selecionada não pôde ser lida.");pendingImport=data.perfume;showPreview(pendingImport);if(confirm(`Encontrei “${pendingImport.title}”${pendingImport.brand?` de ${pendingImport.brand}`:""}.\n\nQueres preencher a ficha?`))applyImport(pendingImport);else status("Ficha encontrada. Não alterei os campos.")}catch(e){status(e?.message||"Não foi possível abrir esta ficha.","error")}finally{setBusy(false)}}
async function importByUrl(){const url=(document.getElementById("parfumoUrl")?.value||"").trim();if(!url){status("Cola primeiro o URL da ficha do Parfumo.","error");return}await loadSuggestion(url)}
function showPreview(p){document.getElementById("parfumoPreview")?.classList.add("show");const img=document.getElementById("parfumoPreviewImg");if(img){img.src=p.image||"icon.svg";img.alt=`Frasco de ${p.title||"perfume"}`;img.onerror=()=>{img.src="icon.svg"}}const t=document.getElementById("parfumoPreviewName");if(t)t.textContent=p.title||"Perfume";const m=document.getElementById("parfumoPreviewMeta");if(m)m.textContent=[p.brand,p.year?String(p.year):"",p.rating?`Parfumo ${p.rating}/10`:""].filter(Boolean).join(" · ")}
function setValue(id,v,overwrite=false){const e=document.getElementById(id);if(!e||v===undefined||v===null||v==="")return;if(overwrite||!String(e.value||"").trim())e.value=v}
function applyImport(p){setValue("brand",p.brand);setValue("name",p.title,true);if(p.accords?.length)setValue("profile",p.accords.join(" · "));if(p.topNotes?.length)setValue("topNotes",p.topNotes.join(", "));if(p.heartNotes?.length)setValue("heartNotes",p.heartNotes.join(", "));if(p.baseNotes?.length)setValue("baseNotes",p.baseNotes.join(", "));if(!document.getElementById("sourceUrl")?.value?.trim())setValue("sourceUrl",p.url);status("Ficha preenchida. Mantive as tuas avaliações e restantes campos pessoais.","ok")}
function patchSavedImage(){if(!pendingImport?.image)return;const id=document.getElementById("perfumeId")?.value||"",name=(document.getElementById("name")?.value||"").trim(),brand=(document.getElementById("brand")?.value||"").trim(),imageUrl=pendingImport.image,parfumoUrl=pendingImport.url||"";setTimeout(async()=>{try{const arr=JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]");if(!Array.isArray(arr))return;let item=id?arr.find(x=>x.id===id):null;if(!item)item=[...arr].sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0)).find(x=>String(x.name||"").trim()===name&&String(x.brand||"").trim()===brand);if(!item)return;item.imageUrl=imageUrl;item.parfumoUrl=parfumoUrl;localStorage.setItem(STORAGE_KEY,JSON.stringify(arr));const {data}=await supabase.auth.getSession();if(data.session?.user&&item.id)await supabase.from("perfumes").update({image_url:imageUrl}).eq("id",item.id);window.dispatchEvent(new CustomEvent("oud-haenir-image-updated",{detail:{id:item.id,name:item.name,imageUrl}}))}catch(e){console.warn(e)}},250)}
function resetForDialog(){pendingImport=null;document.getElementById("parfumoPreview")?.classList.remove("show");clearSuggestions();const u=document.getElementById("parfumoUrl");if(u)u.value="";status("Podes pesquisar só por nome, só por marca, ou pelos dois.")}
function esc(v=""){return String(v).replace(/[&<>']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;"}[c]))}
function init(){injectStyles();ensureUi();document.getElementById("perfumeForm")?.addEventListener("submit",patchSavedImage,true);document.addEventListener("click",e=>{if(e.target.closest("#addBtn")||e.target.closest("#floatingAdd")||e.target.closest(".edit"))setTimeout(resetForDialog,30)})}
init();