import {initSupabase,listenAuth,getCurrentUser,signInWithGoogle,signOut,fetchOwnWatches,upsertWatch,deleteWatchRecord,uploadWatchPhoto,getWatchPhotoUrl,deleteWatchPhoto,getFriendships,findProfileByEmail,sendFriendRequest,acceptFriendRequest,removeFriendship,getMyWatchPrivacy,setWatchPrivacy,getFriendWatches} from "./supabase.js";
const views={home:byId("homeView"),list:byId("listView"),friends:byId("friendsView"),friendCollection:byId("friendCollectionView"),cloud:byId("cloudView")};
const state={user:null,data:[],category:"collection",sort:"updated",search:"",friends:[],friendUser:null,friendStatus:"collection",pendingPhoto:null,removePhoto:false};
const meta={collection:["Coleção","PRIVATE COLLECTION","Os relógios que já fazem parte da tua rotação."],build:["Build","PROJECT WATCHES","Projetos montados ou em desenvolvimento."],wishlist:["Wishlist","RADAR","Relógios e marcas que queres acompanhar."]};
wire(); clock(); boot();
async function boot(){
 try{await initSupabase(); state.user=await getCurrentUser(); if(state.user) await enterApp(); else showLogin();
 listenAuth(async(event,user)=>{state.user=user;if(user&&["SIGNED_IN","INITIAL_SESSION","TOKEN_REFRESHED"].includes(event)) await enterApp(); if(!user&&event==="SIGNED_OUT") showLogin()});
 }catch(e){byId("gateMessage").textContent="Não foi possível ligar ao Supabase."}
}
async function enterApp(){byId("loginGate").classList.add("hidden");byId("appShell").classList.remove("hidden");byId("cloudUserValue").textContent=state.user.email||state.user.id;state.data=loadLocal(state.user.id);await syncOwn(false);await loadFriends();await loadPrivacy();show("home")}
function showLogin(){byId("appShell").classList.add("hidden");byId("loginGate").classList.remove("hidden");state.data=[];state.friends=[]}
function storageKey(uid){return`b612_vault_user_${uid}`}
function loadLocal(uid){try{return JSON.parse(localStorage.getItem(storageKey(uid))||"[]")}catch{return[]}}
function saveLocal(){if(state.user)localStorage.setItem(storageKey(state.user.id),JSON.stringify(state.data))}
async function syncOwn(showMsg=true){try{if(showMsg)msg("A sincronizar…");const cloud=await fetchOwnWatches();const c=new Map(cloud.map(x=>[x.id,x]));for(const l of state.data){const r=c.get(l.id);if(!r||(l.updatedAt||0)>(r.updatedAt||0)){await upsertWatch(l);c.set(l.id,l)}}state.data=[...c.values()].sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0));saveLocal();renderHome();renderList();if(showMsg)msg("Sincronização concluída.")}catch(e){msg("Erro ao sincronizar: "+e.message)}}
function wire(){
 byId("gateGoogleBtn").onclick=()=>signInWithGoogle().catch(e=>byId("gateMessage").textContent=e.message);
 document.querySelectorAll("[data-category]").forEach(b=>b.onclick=()=>openCategory(b.dataset.category));
 byId("friendsEntry").onclick=async()=>{await loadFriends();show("friends")};document.querySelectorAll(".homeBtn").forEach(b=>b.onclick=()=>show("home"));document.querySelectorAll(".cloudBtn").forEach(b=>b.onclick=()=>show("cloud"));byId("homeCloudBtn").onclick=()=>show("cloud");
 byId("homeAddBtn").onclick=()=>openWatch();byId("listAddBtn").onclick=()=>openWatch();byId("searchInput").oninput=e=>{state.search=e.target.value.toLowerCase();renderList()};byId("sortSelect").onchange=e=>{state.sort=e.target.value;renderList()};
 byId("syncNowBtn").onclick=()=>syncOwn(true);byId("logoutBtn").onclick=async()=>{if(confirm("Fazer log off?")){await signOut();showLogin()}};
 byId("addFriendBtn").onclick=addFriend;byId("backFriendsBtn").onclick=()=>show("friends");document.querySelectorAll("[data-friend-status]").forEach(b=>b.onclick=()=>openFriendCategory(b.dataset.friendStatus));
 byId("privacyCollection").onchange=e=>savePrivacy("collection",e.target.value);byId("privacyBuild").onchange=e=>savePrivacy("build",e.target.value);byId("privacyWishlist").onchange=e=>savePrivacy("wishlist",e.target.value);
 byId("exportBtn").onclick=exportBackup;byId("importInput").onchange=importBackup;
 byId("closeDialog").onclick=closeWatch;byId("cancelBtn").onclick=closeWatch;byId("watchForm").onsubmit=saveWatch;byId("deleteBtn").onclick=deleteWatch;byId("status").onchange=mode;byId("wishlistType").onchange=mode;byId("photoInput").onchange=photoPick;byId("removePhotoBtn").onclick=()=>{state.pendingPhoto=null;state.removePhoto=true;preview("")};
}
function show(name){Object.entries(views).forEach(([k,v])=>v.classList.toggle("hidden",k!==name))}
function openCategory(cat){state.category=cat;state.search="";byId("searchInput").value="";const m=meta[cat];byId("listTitle").textContent=m[0];byId("listEyebrow").textContent=m[1];byId("listIntro").textContent=m[2];renderList();show("list")}
function renderHome(){for(const s of ["collection","build","wishlist"])byId("count"+cap(s)).textContent=state.data.filter(x=>x.status===s).length;byId("countFriends").textContent=state.friends.filter(f=>f.status==="accepted").length}
function renderList(){const grid=byId("watchGrid"),empty=byId("emptyState");grid.innerHTML="";let items=state.data.filter(x=>x.status===state.category&&(!state.search||[x.brand,x.model,x.reference,x.movement].join(" ").toLowerCase().includes(state.search)));items.sort((a,b)=>state.sort==="name"?`${a.brand} ${a.model}`.localeCompare(`${b.brand} ${b.model}`):(b.updatedAt||0)-(a.updatedAt||0));if(!items.length){empty.classList.remove("hidden");empty.textContent="Sem registos nesta categoria.";return}empty.classList.add("hidden");items.forEach(x=>grid.appendChild(card(x,true)))}
function card(x,editable=false){const a=document.createElement("article");a.className="watch-card"+(editable?"":" friend-watch");const wrap=document.createElement("div");wrap.className="watch-image-wrap";const img=document.createElement("img");img.className="watch-image fallback";img.src=placeholder();wrap.append(img);if(x.imageStoragePath)getWatchPhotoUrl(x.imageStoragePath).then(u=>{img.src=u;img.classList.remove("fallback")}).catch(()=>{});const body=document.createElement("div");body.className="watch-body";body.innerHTML=`<div class="brand">${esc(x.brand||"Sem marca")}</div><h3 class="model">${esc(x.model||x.brand||"Sem nome")}</h3><div class="specs">${esc([x.reference,x.movement,x.diameter?x.diameter+" mm":"",x.year].filter(Boolean).join(" · "))}</div>${editable?`<div class="price-row"><span class="price-label">${x.status==="wishlist"?"Preço alvo":"Custo aquisição"}</span><strong class="price">${money(x.purchasePrice)}</strong></div>`:`<div class="shared-note">Partilhado pelo proprietário</div>`}`;a.append(wrap,body);if(editable){const hit=document.createElement("button");hit.className="card-hit";hit.onclick=()=>openWatch(x.id);a.prepend(hit)}return a}
async function loadFriends(){try{state.friends=await getFriendships();renderFriends();renderHome()}catch(e){byId("friendMessage").textContent=e.message}}
function renderFriends(){const req=byId("requestsList"),fr=byId("friendsList");req.innerHTML="";fr.innerHTML="";state.friends.forEach(f=>{const div=document.createElement("div");div.className="social-item";div.innerHTML=`<div class="social-copy"><strong>${esc(f.display_name||"Utilizador")}</strong><span>${f.status==="pending"?(f.direction==="incoming"?"Pedido recebido":"Pedido enviado"):"Amigo"}</span></div>`;const acts=document.createElement("div");acts.className="social-actions";if(f.status==="pending"&&f.direction==="incoming"){const b=button("Aceitar","primary-btn",async()=>{await acceptFriendRequest(f.friendship_id);await loadFriends()});acts.append(b)}if(f.status==="accepted"){acts.append(button("Ver","ghost-btn",()=>openFriend(f)))}acts.append(button(f.status==="accepted"?"Remover":"Cancelar","ghost-btn",async()=>{await removeFriendship(f.friendship_id);await loadFriends()}));div.append(acts);(f.status==="accepted"?fr:req).append(div)});if(!req.children.length)req.innerHTML='<div class="cloud-copy">Sem pedidos.</div>';if(!fr.children.length)fr.innerHTML='<div class="cloud-copy">Ainda sem amigos.</div>'}
async function addFriend(){const email=byId("friendEmail").value.trim();if(!email)return;try{byId("friendMessage").textContent="A procurar…";const p=await findProfileByEmail(email);if(!p){byId("friendMessage").textContent="Não encontrei um utilizador com esse email.";return}if(state.friends.some(f=>f.other_user_id===p.user_id)){byId("friendMessage").textContent="Já existe um pedido ou amizade com esta pessoa.";return}await sendFriendRequest(p.user_id);byId("friendMessage").textContent=`Pedido enviado a ${p.display_name||email}.`;byId("friendEmail").value="";await loadFriends()}catch(e){byId("friendMessage").textContent=e.message}}
function openFriend(f){state.friendUser=f;byId("friendName").textContent=f.display_name||"Amigo";openFriendCategory("collection");show("friendCollection")}
async function openFriendCategory(status){state.friendStatus=status;document.querySelectorAll("[data-friend-status]").forEach(b=>b.classList.toggle("active",b.dataset.friendStatus===status));const grid=byId("friendWatchGrid"),empty=byId("friendEmpty");grid.innerHTML="";empty.classList.add("hidden");try{const items=await getFriendWatches(state.friendUser.other_user_id,status);if(!items.length){empty.classList.remove("hidden");empty.textContent="Sem itens partilhados nesta categoria ou categoria privada.";return}items.forEach(x=>grid.appendChild(card(x,false)))}catch(e){empty.classList.remove("hidden");empty.textContent="Esta categoria não está disponível."}}
async function loadPrivacy(){try{const p=await getMyWatchPrivacy();byId("privacyCollection").value=p.collection_visibility;byId("privacyBuild").value=p.builds_visibility;byId("privacyWishlist").value=p.wishlist_visibility}catch(e){}}
async function savePrivacy(cat,val){try{await setWatchPrivacy(cat,val);msg("Privacidade atualizada.")}catch(e){msg(e.message)}}
function openWatch(id=null){state.pendingPhoto=null;state.removePhoto=false;byId("watchForm").reset();byId("watchId").value="";byId("imageStoragePath").value="";byId("deleteBtn").classList.toggle("hidden",!id);byId("status").value=id?"collection":state.category;preview("");if(id){const x=state.data.find(v=>v.id===id);if(x){byId("watchId").value=x.id;for(const k of ["status","wishlistType","brand","model","reference","movement","diameter","year","purchasePrice","imageStoragePath","link","casePart","dialPart","handsPart","strapPart","notes"])if(byId(k))byId(k).value=x[k]??"";if(x.imageStoragePath)getWatchPhotoUrl(x.imageStoragePath).then(preview).catch(()=>{})}}mode();byId("watchDialog").showModal()}
function closeWatch(){byId("watchDialog").close()}
function mode(){byId("wishlistTypeWrap").classList.toggle("hidden",byId("status").value!=="wishlist")}
function photoPick(e){const f=e.target.files?.[0];if(!f)return;state.pendingPhoto=f;state.removePhoto=false;preview(URL.createObjectURL(f))}
function preview(url){const p=byId("photoPreview"),r=byId("removePhotoBtn");if(url){p.src=url;p.classList.remove("hidden");r.classList.remove("hidden")}else{p.removeAttribute("src");p.classList.add("hidden");r.classList.add("hidden")}}
async function saveWatch(e){e.preventDefault();try{const id=byId("watchId").value||crypto.randomUUID();const old=state.data.find(x=>x.id===id);const x={id,status:byId("status").value,wishlistType:byId("wishlistType").value,brand:byId("brand").value.trim(),model:byId("model").value.trim(),reference:byId("reference").value.trim(),movement:byId("movement").value.trim(),diameter:num(byId("diameter").value),year:num(byId("year").value),purchasePrice:num(byId("purchasePrice").value),imageStoragePath:byId("imageStoragePath").value,link:byId("link").value.trim(),casePart:byId("casePart").value.trim(),dialPart:byId("dialPart").value.trim(),handsPart:byId("handsPart").value.trim(),strapPart:byId("strapPart").value.trim(),notes:byId("notes").value.trim(),updatedAt:Date.now()};if(!x.brand&&!x.model)throw new Error("Indica marca ou modelo.");if(state.removePhoto&&old?.imageStoragePath){try{await deleteWatchPhoto(old.imageStoragePath)}catch{}x.imageStoragePath=""}if(state.pendingPhoto){const path=await uploadWatchPhoto(state.pendingPhoto,id,t=>byId("photoStatus").textContent=t);if(old?.imageStoragePath&&old.imageStoragePath!==path)try{await deleteWatchPhoto(old.imageStoragePath)}catch{}x.imageStoragePath=path}await upsertWatch(x);const i=state.data.findIndex(v=>v.id===id);if(i>=0)state.data[i]=x;else state.data.unshift(x);saveLocal();renderHome();renderList();closeWatch()}catch(err){alert(err.message)}}
async function deleteWatch(){const id=byId("watchId").value;if(!id||!confirm("Eliminar este registo?"))return;const x=state.data.find(v=>v.id===id);if(x?.imageStoragePath)try{await deleteWatchPhoto(x.imageStoragePath)}catch{}await deleteWatchRecord(id);state.data=state.data.filter(v=>v.id!==id);saveLocal();renderHome();renderList();closeWatch()}
function exportBackup(){const blob=new Blob([JSON.stringify(state.data,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`b612-vault-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
async function importBackup(e){const f=e.target.files?.[0];if(!f)return;try{const arr=JSON.parse(await f.text());if(!Array.isArray(arr))throw new Error("Backup inválido");for(const x of arr)await upsertWatch(x);state.data=await fetchOwnWatches();saveLocal();renderHome();renderList();msg("Backup importado.")}catch(err){alert(err.message)}e.target.value=""}
function clock(){const fn=()=>{byId("nowInfo").textContent=new Intl.DateTimeFormat("pt-PT",{weekday:"short",day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date())};fn();setInterval(fn,30000)}
function msg(t){byId("cloudMessage").textContent=t}
function button(text,cls,fn){const b=document.createElement("button");b.textContent=text;b.className=cls;b.onclick=fn;return b}
function placeholder(){return"data:image/svg+xml;utf8,"+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200"><rect width="200" height="200" fill="#111317"/><circle cx="100" cy="100" r="42" fill="none" stroke="#aaa" stroke-width="7"/></svg>')}
function money(v){return v===""||v==null?"—":new Intl.NumberFormat("pt-PT",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(Number(v))}
function num(v){return v===""?"":Number(v)}function cap(s){return s.charAt(0).toUpperCase()+s.slice(1)}function byId(x){return document.getElementById(x)}function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
